schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "i-know-flowchart"
owner:
  username: "xjy0325"
  id: 201455417
  accepted_at: "2026-09-01T09:18:33Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
